spring:
  application:
    name: IAgentebot

server:
  port: 8085

telegram:
  bot:
   username: ${TELEGRAM_BOT_USERNAME}
   token: ${TELEGRAM_BOT_TOKEN}
   enabled: true

iagente:
   api:
     url: ${IAGENTE_API_URL}    
